### ISSUE TITLE
moving object trajectory

### ISSUE THREAD

**Issue by migueldvb** [KeplerGO/K2ephem#2]
Is it possible to use K2ephem or K2onSilicon to plot the trajectory of a moving object on active silicon for a K2 campaing?

**Comment by barentsen** [comment]
Yep @migueldvb! I've added a rudimentary `--plot` argument to `K2ephem` in v1.2, which was released a few weeks ago.

For example, this command:
```K2ephem --plot --first 12 --last 12 Chiron```
will create a file called `Chiron-c12.png` in your working dir.

(The return message of the command doesn't actually tell you what file it created, I must fix that.)

**Comment by migueldvb** [comment]
Thank you! Closing this issue.
